#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable:
    name: Build extension binaries
    # We only run the main pipeline for main branch or releases
#    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    uses: samansmink/duckdb/.github/workflows/_extension_distribution.yml@fc1b62b6b78d7bc23c2140469131d0799ad09ef2
    with:
      duckdb_version: v0.9.0
      extension_name: azure
      exclude_archs: "linux_amd64_gcc4;linux_amd64;linux_arm64;windows_amd64;osx_amd64"

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable
    uses: ./.github/workflows/_extension_deploy.yml
    with:
      duckdb_version: v0.9.0
      extension_name: azure
      exclude_archs: "linux_amd64_gcc4;linux_amd64;linux_arm64;windows_amd64;osx_amd64"
    secrets: inherit